---
# tasks file for ansible-exa
- name: Download exa v0.9.0 binary archive (.zip) and extract it into /usr/local/bin
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Create symlink 'exa' to 'exa-linux-x86_64'
  file:
    src: /usr/local/bin/exa-linux-x86_64
    dest: /usr/local/bin/exa
    state: link
    mode: '0755'
